spring.application.name=AnchorPay


#Temporary (i can create different for development but right no

#spring.datasource.url=jdbc:h2:mem:anchorpay
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.url=jdbc:mysql://localhost:3307/anchorpay
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.redis.host=localhost
spring.redis.port=6379



jwt.secret=anchorpay_by_aaditya_prajapat_finetch_project_1737
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aadi1737ug@gmail.com
spring.mail.password=zyje mdbt cxod zkjz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

